config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get root "home#index"

  get "/about"=> "home#about"

  get "/contact"=> "contact#new"

  post "/contact"=>"contact#create"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  resources :products do
  resources :reviews, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
# class Product < ApplicationRecord
#
#   validates :title, presence: true, uniqueness: true
#   validates :description, presence: true, length:{minimum: 10}
#   # validates :price, numericality:{minimum: 0}
# after_initialize :set_default
# before_validation :capitalize_title
#
# def self.search(keyword)
#     where(["title ILIKE ?", "%#{keyword}%"]) +
#     where(["description ILIKE ?", "%#{keyword}%"])
#
# end
#
#
# private
#
#   def capitalize_title
#     self.title.capitalize! if title
#   end
#
#   def set_default
#     self.price ||=1
#   end
#
# end
class Product < ApplicationRecord

  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :description, presence: true

  def titleized_title
    title.titleize
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :star, presence: true
end

app/models/user.rb
class User < ApplicationRecord




  has_secure_password
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: true,
            format:  VALID_EMAIL_REGEX

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :products, dependent: :nullify

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||=User.find session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to new_session_path unless user_signed_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  @product = Product.find params[:category_id]
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new

  end

  def create
    @name = params[:name]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, only: [:create, :edit, :destroy, :update, :new]
  PRODUCTS_PER_PAGE=10
  def new
    @product=Product.new
  end

  def create
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product), notice: 'Product Saved!'
    else
      render :new
    end
  end

  def index

    @products=Product.order(created_at: :desc).
                            page(params[:page]).
                            per(PRODUCTS_PER_PAGE)


  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
  end

  def destroy
    product=Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

  def edit
    @product=Product.find params[:id]
  end
  def update
    @product = Product.find params[:id]
    if @product.update params.require(:product).permit([:title, :description, :price])
    redirect_to product_path(@product)
  else
    render :edit
  end
  end
  def product_params
    params.require(:product).permit([:title, :description, :price])
  end

 private

 def find_product
   @product = Product.find params[:id]
 end

 def find_params
   params.require(:product).permit(:title, :description, :price, :cataegory_id)
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
      @product=Product.find params[:product_id]
      review_params = params.require(:review).permit(:body, :star)
      @review = Review.new review_params
      @review.product = @product
      if @review.save
      redirect_to product_path(@product), notice: 'Review created!'
    else
      flash[:alert] = 'Please fix errors below'
      render 'products/show'
    end
  end

  def destroy
    pr=Product.find params[:product_id]
    re = Review.find params[:id]
    re.destroy
    redirect_to product_path(pr), notice: 'Review deleted'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong emails or password"
      render :new
    end

  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed Out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      flash[:alert] = "Fix errors below"
      render :new
    end
  end
  private

    def user_params
      params.require(:user).permit( :first_name,
                                    :last_name,
                                    :email,
                                    :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<h1>New Product</h1>
<%= @product.errors.full_messages.join(", ") %>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div>
    <select category="Category [role_id]" :category_id>
      <option value="">All</option>
      <option value="1" selected="selected">Administrator</option>
      <option value="2">User</option>
      <option value="3">Editor</option>
    </select>
  </div>
  <%= f.submit %>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Form</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>
<div>

<select category="Category [role_id]">
  <option value="">All</option>
  <option value="1" selected="selected">Administrator</option>
  <option value="2">User</option>
  <option value="3">Editor</option>
</select>
</div><br>

<% @products.each do |que| %>
<%= link_to que.title, product_path(que) %>
<hr>

<% end %>
<%= paginate @products %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p>
  <%= @product.description %>
</p>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Delete", product_path(@product),
                      method: :delete,
                      data: {confirm: "Are you sure?"} %>
<hr>

<h2>Create a Review</h2>

<%#= form_for @review, url: question_answers_path(@product) do |f| %>
<%#
  form_for [@product, @review]
  this will generate a form for @review. For example if you have a field `description`
  the `name` attribute will actually be: review[description]

  the @product part is only used to generate the action url for the form.

  If @review is not persisted the url will be: question_answers_path(@product)
  If @review is persisted the url will:        question_answer_path(@product, @review)
 %>
<%= @review.errors.full_messages.join(", ")  %>
<%= form_for [@product, @review] do |f| %>
  <div>
    <%= f.text_area :body %></br>
    <%=f.number_field :star %>
  </div>
  <div>
    <select category="Category [role_id]">
      <option value="">All</option>
      <option value="1" selected="selected">Administrator</option>
      <option value="2">User</option>
      <option value="3">Editor</option>
    </select>
  </div>
  <%= f.submit %>
<% end %>

<h2>Reviews</h2>
<% @product.reviews.each do |ans| %>
  <%= ans.body %>
  <%= ans.star %>
  <%= link_to 'Delete', product_review_path(@product, ans),
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>