config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get root "home#index"

  get "/about"=> "home#about"

  get "/contact"=> "contact#new"

  post "/contact"=>"contact#create"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  resources :products do
  resources :reviews, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
# class Product < ApplicationRecord
#
#   validates :title, presence: true, uniqueness: true
#   validates :description, presence: true, length:{minimum: 10}
#   # validates :price, numericality:{minimum: 0}
# after_initialize :set_default
# before_validation :capitalize_title
#
# def self.search(keyword)
#     where(["title ILIKE ?", "%#{keyword}%"]) +
#     where(["description ILIKE ?", "%#{keyword}%"])
#
# end
#
#
# private
#
#   def capitalize_title
#     self.title.capitalize! if title
#   end
#
#   def set_default
#     self.price ||=1
#   end
#
# end
class Product < ApplicationRecord

  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :description, presence: true

  def titleized_title
    title.titleize
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :star, presence: true
end

app/models/user.rb
class User < ApplicationRecord




  has_secure_password
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: true,
            format:  VALID_EMAIL_REGEX

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :products, dependent: :nullify

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new

  end

  def create
    @name = params[:name]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, only: [:create, :edit, :destroy, :update, :new]
  PRODUCTS_PER_PAGE=10
  def new
    @product=Product.new
  end

  def create
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product), notice: 'Product Saved!'
    else
      render :new
    end
  end

  def index

    @products=Product.order(created_at: :desc).
                            page(params[:page]).
                            per(PRODUCTS_PER_PAGE)


  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
  end

  def destroy
    product=Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

  def edit
    @product=Product.find params[:id]
  end
  def update
    @product = Product.find params[:id]
    if @product.update params.require(:product).permit([:title, :description, :price])
    redirect_to product_path(@product)
  else
    render :edit
  end
  end
  def product_params
    params.require(:product).permit([:title, :description, :price])
  end

 private

 def find_product
   @product = Product.find params[:id]
 end

 def find_params
   params.require(:product).permit(:title, :description, :price, :cataegory_id)
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
      @product=Product.find params[:product_id]
      review_params = params.require(:review).permit(:body, :star)
      @review = Review.new review_params
      @review.product = @product
      if @review.save
      redirect_to product_path(@product), notice: 'Review created!'
    else
      flash[:alert] = 'Please fix errors below'
      render 'products/show'
    end
  end

  def destroy
    pr=Product.find params[:product_id]
    re = Review.find params[:id]
    re.destroy
    redirect_to product_path(pr), notice: 'Review deleted'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      flash[:alert] = "Fix errors below"
      render :new
    end
  end
  private

    def user_params
      params.require(:user).permit( :first_name,
                                    :last_name,
                                    :email,
                                    :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse" style = 'width: 100%; background-color: #111111;'>
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%=link_to 'Home', root_path%></li>
      <li><%=link_to 'About', about_path%></li>
      <li class='dropdown'>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%=link_to 'Show Products', products_path%></li>
          <li><%=link_to 'Add a Product', new_product_path%></li>
        </ul>
      </li>
      <li><%=link_to 'Contact', contact_path%></li>
      <% if user_signed_in? %>
      Welcome <%= current_user.full_name %>
      <%= link_to "Sign Out", sessions_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      |
      <%= link_to "Sign In", new_session_path %>
    <% end %>
    </ul>
  </div>
</nav>
    <%#link_to "Home", root_path %>

    <%# link_to "About", about_path %>

    <%# link_to "Contact US", contact_path %>

    <%# link_to 'New Product', new_product_path %>

    <%#link_to 'List producs', products_path %>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>